### PR TITLE
Fix persisting the scrollTop on item updates

### LINKED ISSUE #31: Need to persist ScrollTop()
I've noticed an issue of persisting the scrollTop when a new `items` array is passed in. 

The scrollTop `resets` to the beginning of the `_startAt`, when what we REALLY want is to persist the `scrollTop` at the current pixel. So right now we have "index-persistance" but not "scrollTop-persistance" when receiving a new items array. 

This appears as a glitch in cases where we have scrolled part-way through an item:

Let's say we are looking at an `Item 8`, but have scrolled part-way through it . . . 

|-------
| Item 8 // Top half is cut off. Looking good!
|
|-------
|
| Item 9
|
|-------
| 
| Item 10 // Last item
| 
|-------

Let's say scrollBottomed, and we receive more items in our items array. We would expect the scrollTop to remain at the current pixel, but it instead resets to the beginning of the current item index:

|-------
|
| Item 8 // Top half is exposed, which is not the desired UI. Looking glitchy!
|
|-------
|
| Item 9
|
|-------
| 
| Item 10 // Last item
| 
|-------

I will try and work on a solution for this. But I think it has to do with calling `caculateVisibleItems(positionIndex)` whenever we receive an new items array. Perhaps this is not the desired logic when receiving a new items array?

### PR DESCRIPTION
**Pull request by flexyford**
Fixes #31 

`scrollTo` was being called too frequently. It's necessary to scroll to a new item on init, and whenever the `positionIndex` attribute changes. Here we implement an observer on `_positionIndex`, which only fires whenever `positionIndex` changes.

In addition we have written [tests](https://github.com/jasonmit/virtual-each/blob/persist-scroll-top/tests/unit/virtual-each-test.js#L281-L284) which exercise the related issues.

### CODE REVIEW

File: addon/components/virtual-each.js [hunk 1]
```diff
@@ -178,7 +191,7 @@ const VirtualEachComponent = Component.extend(EventListenerMixin, DefaultAttrsMi
         _totalHeight: Math.max(get(items, 'length') * this.getAttr('itemHeight'), 0)
       });
 
-      if (attrs.newAttrs.hasOwnProperty('items') || attrs.newAttrs.hasOwnProperty('positionIndex')) {
```
Comment (flexyford) [inline addon/components/virtual-each.js]: We do not ever scrollTo when items change, because this is handled by observers on `_items`

File: addon/components/virtual-each.js [hunk 2]
```diff
@@ -163,11 +164,13 @@ const VirtualEachComponent = Component.extend(EventListenerMixin, DefaultAttrsMi
     const sanitizedIndex = Math.min(startingIndex, maxVisibleItemTop);
     const sanitizedPadding = (startingPadding > maxPadding) ? maxPadding : startingPadding;
 
-    this.calculateVisibleItems(sanitizedIndex);
-    this.$().scrollTop(sanitizedPadding);
-  },
+    emberRun.scheduleOnce('afterRender', () => {
```
Comment (jasonmit) [inline addon/components/virtual-each.js]: We should cancel the scheduling on destroy just to be guard against this being dequeued when the component is destroyed || destroying

Comment (flexyford) [inline addon/components/virtual-each.js]: How would one go about implementing that?

Comment (jasonmit) [inline addon/components/virtual-each.js]:
```js
this.scheduledRender = emberRun.scheduleOnce('afterRender', () => {
});
```

```js
willDestroyElement() {
  this._super(...arguments);
  Ember.run.cancel(this.scheduledRender);
}
```

Comment (flexyford) [inline addon/components/virtual-each.js]: :+1:

**Comment by flexyford** [comment]
Thanks @jasonmit this is a great suggestion. I'm using `virtual-each` and am running into memory leaks during testing. @Robdel12 I wonder if this last commit will fix our issues :grin:

**Comment by jasonmit** [comment]
Nice!  Merge when you are ready
